# These are supported funding model platforms

github: [shgopher]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: shgopher# Replace with a single Patreon username
open_collective: shgopher# Replace with a single Open Collective username
ko_fi: shgopher# Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: shgopher# Replace with a single Liberapay username
issuehunt: shgopher# Replace with a single IssueHunt username
otechie: shgopher# Replace with a single Otechie username
custom: shgopher# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
